drop table tblUser if exists;
create table tblUser (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(220) not null,
  firstName varchar(50),
  lastName varchar(50),
  email varchar(100),
  password varchar(100) not null,
  salt varchar(100) not null,
  accountType varchar(50) NOT NULL
);

drop table tblSkills if exists;
create table tblSkills (
  skillsID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  skill1 bit,
  skill2 bit,
  skill3 bit,
  skill4 bit,
  skill5 bit,
  skill6 bit
);

drop table tblJobs if exists;
create table tblJobs (
  jobsID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  freelancerID INT,
  jobPosterID INT,
  jobID VARCHAR(254),
  jobAccepted bit,
  jobAcceptedDate DATETIME,
  jobDeclined bit,
  jobCompleted bit,
  jobCompletedDate DATETIME
);