drop table tblUser if exists;
create table tblUser (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(220) not null,
  firstName varchar(50),
  lastName varchar(50),
  email varchar(100),
  password varchar(100) not null,
  salt varchar(100) not null,
  accountType varchar(50) NOT NULL
);

drop table tblSkills if exists;
create table tblSkills (
  skillID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  value  VARCHAR(250) NOT NULL
);

drop table tblSkills_User if exists;
create table tblSkills_User (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  userID INT,
  skillID  INT
);

drop table tblJobs if exists;
create table tblJobs (
  jobsID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  freelancerID INT,
  jobPosterID INT NOT NULL,
  jobDesc VARCHAR(250) NOT NULL,
  jobAccepted bit,
  jobAcceptedDate DATETIME,
  jobCompleted bit,
  jobCompletedDate DATETIME,
  deleteStatus bit
);

drop table tblFreelancer if exists;
create table tblFreelancer (
  freelancerID integer primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  userId INT
);

drop table tblDeclined if exists;
-- Declined Table, holds what Jobs a Freelancer has declined, a Freelancer can decline many jobs over
-- a period of time, but only decline a single job once
create table tblDeclined (
  declinedID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  freelancerID INT NOT NULL,
  jobsID INT NOT NULL
);

drop table tblProfile if exists;
-- Profile Table, holds a users profile both freelancer and job poster, although some fields will only relate to
-- one user type, others will be for both types
create table tblProfile (
  profileID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  userId INT,
  location VARCHAR(25),
  address1 VARCHAR(50),
  suburb VARCHAR(50),
  state VARCHAR(10),
  postCode VARCHAR(12),
  bio VARCHAR(250),
  education VARCHAR(25),
  workExperience VARCHAR(25)
);
